apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: wasmtime-slight
handler: slight
scheduling:
  nodeSelector:
    wasm/wasmtime-slight-v1: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasm-slight
spec:
  replicas: 5
  selector:
    matchLabels:
      app: wasm-slight
  template:
    metadata:
      labels:
        app: wasm-slight
    spec:
      runtimeClassName: wasmtime-slight
      containers:
        - name: hello-slight
          image:  docker.io/jsturtevant/qs-wasm-slight:all-in-one
          command: ["/"]
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 500m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: wasm-slight
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: wasm-slight
---
