FROM --platform=${BUILDPLATFORM} rust:1.64 AS build
WORKDIR /opt/build
COPY . .
RUN rustup target add wasm32-wasi && cargo build --target wasm32-wasi --release

FROM mcr.microsoft.com/oss/kubernetes/windows-host-process-containers-base-image:v1.0.0
COPY --from=build /opt/build/target/wasm32-wasi/release/http_server_lib.wasm ./app.wasm
COPY --from=build /opt/build/slightfile.toml .